CREATE TABLE LOGIN_COMPANY 
(
ID NUMBER PRIMARY KEY, 
USERNAME VARCHAR2(100) NOT NULL UNIQUE,
PASSWORD VARCHAR2(100) NOT NULL,
COMPANY_NAME NVARCHAR2(100) NOT NULL,
TOKEN VARCHAR2(200),
LOGIN_DATE DATE DEFAULT SYSDATE ,  
ACTIVE INTEGER DEFAULT 1 
);