CREATE OR REPLACE FUNCTION DBLESSON1.GET_STUDENT_LIST_FUNC RETURN SYS_REFCURSOR
IS 
RESULT SYS_REFCURSOR;
BEGIN
OPEN RESULT FOR
SELECT ID,NAME,SURNAME,ADDRESS,DOB,PHONE,EMAIL FROM STUDENT
WHERE ACTIVE = 1;
RETURN RESULT;
END;

CREATE OR REPLACE FUNCTION DBLESSON1.join_strings
( string1 VARCHAR2
, string2 VARCHAR2 ) RETURN VARCHAR2 IS
BEGIN
RETURN string1 ||' '|| string2||'.';
END;

CREATE OR REPLACE FUNCTION DBLESSON1.TEST_FUNC(NUM1 IN NUMBER,NUM2 IN NUMBER) 
RETURN NUMBER 
IS 
CEM NUMBER;
BEGIN
CEM := NUM1+NUM2;
RETURN CEM;
END;